# NumPy 入門　レッスン１

## 1.1 NumPyとは？

科学技術計算やWebデータの分析などの大規模なデータを取り扱う場合、多次元かつ大量のベクトル（=配列）の演算が必要になります。

PythonはCやJavaなどのコンパイラ言語と比較するとかなり遅いため、そうった演算を行うと難儀するのですが、NumPyの配列オブジェクト「ndarray」を使用することで高速なデータ処理が可能となります。

In [2]:
import numpy as np
import random as rd
import sys
np.set_printoptions(threshold=sys.maxsize)

In [3]:
list_ = [56, 54543, 56]
print(list_[2])

56


インポートする際はnpと名前を付けるのが一般的です。例えば、numpyをインポートし、3行3列の行列を生成する場合は以下のように記述します。（詳細は別途説明します。）

In [4]:
gg = np.array([[11 , 12, 13], [21, 22, 23], [31, 32, 33]])
print(gg)

hh = 'string, 文字列'
print(type(hh))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'str'>


一次元と二次元（例）：
-  この下にあるアレー（配列）は一次元。

In [40]:
np.array([114 , 1232, 1354])

array(['114', '1232', 'ff'], dtype='<U21')

- 次は二次元、二次元であればコマで各行は分別されています。

In [68]:
ll = np.array([[[114 , 1232, 1354], 
                [34354, 5645, 4343], 
                [239403, 4943, 321], 
                [43, 1920, 4332]],
               
              [[114 , 1232, 1354], 
               [34354, 5645, 6], 
               [239403, 4943, 321], 
               [43, 1920, 4332]]])

print(ll)

[[[   114   1232   1354]
  [ 34354   5645   4343]
  [239403   4943    321]
  [    43   1920   4332]]

 [[   114   1232   1354]
  [ 34354   5645      6]
  [239403   4943    321]
  [    43   1920   4332]]]


## 1.2 用語について

NumPyで用意されている配列はndarrayというNumPy独自の型なのですが、今後このndarrayでベクトルや行列を表します。「NumPyの配列」だと少し長いので今後は単純に「array」もしくは「配列」と記述します。

また、実はNumPyには配列とは別に「matrix（行列）」という型があるのですが、あまり使われなくなりつつあるらしいため、当サイトでは線形代数と同様、単純に2次元の配列のことを行列と呼称します。

### 1.2.1 リストとどう違いますか？
リストも二次元のリストを作れます。が、Numpyに考慮されている機能などより多いと使いやすいため、二次元以上の配列（array）は一般的にNumpyでデータを取り扱います。（先生は画像とか描いたほうがいい）。

In [5]:
x = np.array([1, 0, 1])
print(x)

[1 0 1]


In [6]:
# ここで試してみよう


配列はarray関数にリストやタプルのようなシーケンシャルオブジェクトを指定することで生成することができます。

## 1.3 さまざまな配列生成方法

配列の生成時に範囲、間隔、個数、型などを指定することができます。

### 1.3.1 範囲指定 、間隔指定

arangeを使用すると範囲や間隔を指定することができます。

In [86]:
x = np.arange(10, 20)    # 1以上10未満の配列を生成
y = np.arange(10, 100, 9) # 1以上10未満、間隔2の配列を生成

print(x)
print(y)

[10 11 12 13 14 15 16 17 18 19]
[10 19 28 37 46 55 64 73 82 91]


In [8]:
# ここで試してみよう submit by monday.


### 1.3.2 個数指定

linspaceを使用すると個数を指定することができます。

In [94]:
gg = np.linspace(1, 20, 20) # 1〜2で5個の要素
print(gg)

# lin linear
# space 

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


### 1.3.3 データタイプを指定する
データタイプまだ覚えていますか？

numpyには独自の型があり、引数dtypeで適切な型設定することによりメモリ使用量を節約することができます。詳細な型や型変換については別項にて説明します。上のサンプルのように型を指定しない場合はnumpy.int64となります。例えば、float32を指定する場合は以下のように記述します。

In [99]:
gg = np.array([1.3, 0, 1], dtype='float32')
bb = np.array([1.8, 0, 1], dtype='int64')
dd = np.array([1, 0, 1], dtype='str')

# dd = np.array([1, 0, 1], dtype="")

In [105]:
print(gg)
print(bb)
print(dd)

[1.3 0.  1. ]
[1 0 1]
['1' '0' '1']


In [111]:
# give her assignment here
# kl = int(dd)

dd = np.array(["45", "43", "56", "34", "12", "34"])
print(dd)
hh = np.array(dd, dtype="float32")
print(hh)

['45' '43' '56' '34' '12' '34']
[45. 43. 56. 34. 12. 34.]


### 1.3.4 配列へのデータアクセス

リストやタプルのような通常のシーケンシャルオブジェクトと同様に添字でアクセスすることができます。

In [16]:
# 配列を生成
x = np.array([1, 2, 3, 4, 5])
 
# 0番目にアクセス
print(x[0]) # 1
 
# スライスで0番目から2番目未満にアクセス
print(x[0:2]) # array([1, 2])
 
# 最後の要素にアクセス
print(x[-1]) # 5

1
[1 2]
5


二次元の配列の要素もアクセスこうアクセスできます

In [16]:
jj = np.array([[114 , 1232, 1354], 
              [34354, 5645`, 4343], 
              [239403, 4943, 321], 
              [43, 1920, 4332]])

print(jj[0][2])
print(jj[0,])
print(jj[0,0:2])

1354
[ 114 1232]


# 1.3 最後の課題

挑戦してみよう。
1. 二つ同じ一次元の配列を作ってください。一つ目はリストで、二つ目はNumPyで作ってください。
2. 
3. 


In [29]:
numpy1 = np.array([1, 7, 3])
print(numpy1)

numpy1 = np.append(numpy1, [34, 4])
print(numpy1)

[1 7 3]
[ 1  7  3 34  4]


In [12]:
list1 = [1, 2, 3]
print(type(list1))
list1.pop()
print(list1)

<class 'list'>
[1, 2]


In [28]:
np.append(numpy1, [4, 5, 6])


[1 7 3]
