# NumPy 入門　レッスン２

## 2.1　復習：NumPy Array作成方法

少しNumPy arrayの作成方法を復習しましょう。前回三つぐらいの方法を紹介しました。ここでまた見てみよう。

In [33]:
import numpy as np
import random as rd
import sys

### 2.1.1 方法の１：最も基本の方法：Arrayを定義する

この方法はnp.arrayの関数を使って、そのアレーの要素を一つ一つ定義する。

In [34]:
number_array = np.array([[11 , 12, 13], [21, 22, 23], [31, 32, 33]])
print(number_array)

string_array = np.array(["great", "reat", "ggg"])
print(string_array)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
['great' 'reat' 'ggg']


In [5]:
# ここで試してください


### 2.1.2 方法の２：個数指定 

linspaceという関数を使う。linspaceは「linear space」から略語されていた。あるいは、線型空間と意味する。使い方も名前通り。

In [35]:
gg = np.linspace(0, 1, 10000) # 1〜2で5個の要素
print(gg)


[0.00000000e+00 1.00010001e-04 2.00020002e-04 ... 9.99799980e-01
 9.99899990e-01 1.00000000e+00]


In [37]:
# ここで試して

def kansuu(var_1 , var_2):
    print(var_1, var_2)
    
kansuu("my name", "Yasin")

my name Yasin


### 2.1.3 方法の３：範囲指定 、間隔指定

arangeを使用すると範囲や間隔を指定することができます。arangeは「a range」からのフレーズで、そのまま「範囲」です。

引数は二つか三つを定義できて、それによって違う結果ができる。
- 二つ定義すればその二つの数値の間に、整数 1 の増加で上昇する。
- 三つだったら、三つ目の数値は増分値を決定する。

In [43]:
x = np.arange(10.1, 20.3)    # 1以上10未満の配列を生成
y = np.arange(1, 100, 1) # 1以上10未満、間隔2の配列を生成

print(x)
print(y)
print(len(y))


[10.1 11.1 12.1 13.1 14.1 15.1 16.1 17.1 18.1 19.1 20.1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
99


In [40]:
# 検討してみよう



## 2.2 NumPy入門 行列の演算

NumPyで基本的な行列を生成する方法について学習した。ここでは生成した行列を計算する方法について学習する。

### 2.2.1 ndarrayの四則演算


In [21]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [22]:
a + b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [46]:
a - b
# b - a

array([[ -9, -18, -27],
       [-36, -45, -54],
       [-63, -72, -81]])

In [48]:
print(a * b)
np.dot(a, b)

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [25]:
a / b

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

一次元のアレーの例：

In [28]:
x + y

array([ 11.1,  21.2,  31.3,  41.4,  51.5,  61.6,  71.7,  81.8,  91.9,
       102. , 112.1])

In [29]:
x - y

array([  9.1,   1. ,  -7.1, -15.2, -23.3, -31.4, -39.5, -47.6, -55.7,
       -63.8, -71.9])

In [30]:
x * y

array([  10.1 ,  112.11,  232.32,  370.73,  527.34,  702.15,  895.16,
       1106.37, 1335.78, 1583.39, 1849.2 ])

In [31]:
x / y

array([10.1       ,  1.0990099 ,  0.63020833,  0.46289753,  0.37700535,
        0.32473118,  0.28956835,  0.26429675,  0.24525745,  0.23039807,
        0.21847826])

**ノート：実際に数学に行列の掛け算は主に二つ方法があって、以上に紹介された掛け算の仕組みは異なっている。それでもこういう仕組みも純粋のデータの整理や処理の場合で役に立てる。**

## 2.3 最後の課題：

練習してみよう。この講座で学んだNumPy機能を使ってみよう。

πって知っている？丸の幾何学的な計算によく使われている値です。π（円周率）はやく3.14と定義されている。
<br>数学で定義されている値が多くて、数学定数と呼ばれている。Pythonはそれに対してモジュールが用意されていて、便利にアクセスできる。次の例に見てください：


In [32]:
import math

print(math.pi)

3.141592653589793


最後の課題はnumpyモジュールの使いに沿って、mathモジュールから円周率を使ってください。

課題は、３行３列の二次元のアレーを作成して、すべての要素は円周率を入れてください。
<br>（ヒント、最初に円周率は変数に代入したほうがいいと思う）。

そこで、上から下へ、左から右へ、配列の要素に 1 から 9 までの整数倍をかける。

In [50]:
var_ = 3.86554

array1 = np.array([var_, var_])
array2 = np.array([1, 2])
array1 * array2

array([3.86554, 7.73108])