# NumPy 入門　レッスン３

## 3.1　numpy.append：配列末尾に要素を追加するappend関数

これに対応するNumPyの関数、np.append関数を紹介します。

listのappendはメソッドでしたが、np.arrayのappendは関数です。同じような動作をする機能ですが、「np.appendは配列(np.array/list)自体を変更しない」という明確な違いがあります

In [1]:
import numpy as np

In [60]:
l = np.array([])
print("結果１", l)
# l = np.append(l, np.array([]))

np.append(l, np.array(['G', 'F', 'G']))
print("結果１", l)

l = np.append(l, np.array(['G', 'F', 'G']))
print("結果２", l)

l = np.append(l, np.array(['G', 'F', 'G']))
print("結果３", l)

結果１ []
結果１ []
結果２ ['G' 'F' 'G']
結果３ ['G' 'F' 'G' 'G' 'F' 'G']


In [61]:
list_ = []
test_ = [5, 6]
print(list_)
list_.append(test_)
print(list_)

[]
[[5, 6]]


axisのことは一旦忘れて、まずは簡単な使い方を確認してみましょう。まずはサンプル配列を作っておきます。



In [65]:
x = np.zeros(10)
print(x)

pp = np.zeros(1000)
# print(pp)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Pythonのappendはlist型のメソッドとして実装されていました。これに対して、NumPyのappendは関数として実装されているので注意が必要です。

appendは非破壊の関数なので、x自体は変わっていないことにも注意。

In [47]:
print(np.append(x, 10))
print(x)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


append関数を試してみよう：
- まず、一次元のアレー（配列）を作成して、
- 五つの要素が入っているアレーを最初のアレーをappendしてください。

```
np.append(元の配列, 追加したい配列, axisで横軸か縦軸に要素を追加する。)
print(5)
```


In [72]:
# ここから
array1 = np.array([10, 10, 10, 10])
print(array1)
print(np.append(array1, 40))

array2 = np.array([60, 60, 60])
array1 = np.append(array1, array2)

print(array1)

[10 10 10 10]
[10 10 10 10 40]
[10 10 10 10 60 60 60]


## 3.2　axisを使って多次元配列に要素追加

axis=0は、valuesを配列として、多次元配列に追加してくれます。第一引数と第二引数の次元数や要素数が揃っていれば、多次元配列にも要素を追加する事ができます。

```
縦軸　＝　axis=0, 横軸　＝　axis=1,
元の配列と追加したい配列を結合する時、axisによってサイズを合わせないといけない

元の配列：
[__, __, __]   [__]
[__, __, __] + [__]
[__, __, __]   [__]
　　　 +　　 　　  ↑ 追加したい配列
[__, __, __]    <- 追加したい配列
               
```


In [34]:
ff = np.ones((2,3))
print(ff * 10)

s = np.array([[1,2,3], [1,2,3]])
print(ff.shape)
print(s.shape)

[[10. 10. 10.]
 [10. 10. 10.]]
(2, 3)
(2, 3)


In [38]:
np.append(ff, s, axis=0)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 2., 3.],
       [1., 2., 3.]])

.shape関数　=> 直接訳すれば、「形」と言えます。その関数の役割もだた配列の形を解明することです。

In [51]:
print(ff.shape)

(2, 3)


また、引数に渡すのはarray_likeなオブジェクトであればいいので、listでも問題なく動作します。

In [32]:
print(np.append(ff, [[10,20,30]], axis=0))

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [10. 20. 30.]]


ですが、次元数が異なる場合や、要素数が異なる場合はValueErrorが起こり失敗するので注意です。

In [53]:
np.append(ff, [10,20,30], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [54]:
np.append(ff, [[10,20]], axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

練習練習練習：
- 4行5列の配列を作ってください
- axis=0の引数を作って、適当な整数をappendしてください

## 3.3　axis=1：多次元配列内のすべての配列に要素を追加

axis=1は、valuesを各配列の要素として、多次元配列に追加してくれます。
操作はaxis=0のときと同様です。


In [30]:
ff = np.ones((2,3))
mm = np.append(ff, np.array([[1],[2]]), axis=1)

print(ff)
print(np.array([[1],[2]]))
print(mm)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1]
 [2]]
[[1. 1. 1. 1.]
 [1. 1. 1. 2.]]


In [26]:
np.append(ff, [[5],[10]], axis=1)

array([[ 1.,  1.,  1.,  5.],
       [ 1.,  1.,  1., 10.]])

axis=0のときと同じく、次元数と要素数に注意しましょう。

In [32]:
np.append(ff, np.array([1,2]), axis=1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 2.]])

## 3.4 最後の課題
append関数はとても重要ですから、最後の課題で練習だけしましょう：
- 6個のゼロが入っている一次元numpyアレーを作って、末尾に３回要素を追加してください。
- 8行10列のnumpyアレーを作って、２回axis=0の方に要素を追加してください。ゼロだけでも構いません。
- そのアレーは１回axis=1の方に要素を追加してください。

In [40]:
zero_arr = np.zeros(6)
zero_arr = np.append(zero_arr, [4, 5, 6])
print(zero_arr)

[0. 0. 0. 0. 0. 0. 4. 5. 6.]


In [43]:
zero_arr2 = np.zeros((8, 10))
# print(zero_arr2)

to_append = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
zero_arr2 = np.append(zero_arr2, to_append, axis=0)
# print(zero_arr2)

zero_arr2 = np.append(zero_arr2, to_append, axis=0)
print(zero_arr2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


In [24]:
zero_arr2 = np.append(zero_arr2, to_append.T, axis=1)
print(zero_arr2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 6.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 8.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 9.]]
